Repository openSUSE/trollolo, pull requests merged in 2018-02, with the labels that each got.

#161 Remove redundant gem --version
  .travis.yml
Labels: test suite

#157 Solve Bundler/OrderedGems RuboCop cop offenses
  .rubocop_todo.yml
  Gemfile
Labels: linters

#158 Solve Performance/HashEachMethods RuboCop cop offenses
  .rubocop_todo.yml
  lib/cli.rb
  lib/scrum/creator.rb
Labels: linters

#159 Solve Layout/DotPosition RuboCop cop offenses
  .rubocop_todo.yml
  spec/integration/create_burndown_spec.rb
  spec/unit/trello_wrapper_spec.rb
Labels: linters

#175 Update ruby-trello
  .travis.yml
  README.md
  spec/unit/cli_spec.rb
  spec/unit/trello_wrapper_spec.rb
  trollolo.gemspec
Labels: bug
